### ISSUE TITLE
About the input normalization

### ISSUE THREAD

**Issue by shiyanpei** [fancoo/WaveGAN-pytorch#2]
Hi , 

 Thanks for your implementation.
 I am curious about whether to normalize the input. I did not find the code that normalize the input to a certain range, but the output activation function of generator is tanh, seems that the audio data are normalized to (-1,1) ,am I right? and how do you normalize it?

Thank you!

**Comment by mazzzystar** [comment]
@shiyanpei sorry for late response. We do actually normalize the input signal with:https://github.com/mazzzystar/WaveGAN-pytorch/blob/9d96a1336adcc4c077ce153092395d8060fba14a/utils.py#L61-L64
