### ISSUE TITLE
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1549616138213/work/aten/src/THC/THCBlas.cu:258

### ISSUE THREAD

**Issue by hinash88** [fancoo/WaveGAN-pytorch#3]
Hello everyone!

I am new to learn audio WavGAN and I am trying to run this code on Linux 16.04 for piano train  [dataset](http://deepyeti.ucsd.edu/cdonahue/mancini_piano.tar.gz) containing 15 (.wav) files. Can anybody please help me why I am having this issue. I am working on:
1- CUDA Version: CUDA-10.0
2- NVIDIA Driver Version: 410.79
3- Simulation details include: Batch Size = 10,  nGPU = 4 (Since I have 4 GPUs GeFORCE RTX 2080)

**Comment by mazzzystar** [comment]
As seen in [this issue](https://github.com/NVIDIA/waveglow/issues/66), the mismatch between the driver version and cuda version lead to this problem.

**Comment by hinash88** [comment]
Thank you for your reply! You are right. I already installed CUDA10.0 which was compatible with my driver version. The problem is pytorch which when installed with pip was not supporting my platform.

I solved this problem by selecting Stable-> Linux->conda->python2.7->CUDA from (https://pytorch.org/).
After that I updated ~/.bashrc by adding path to my installed anaconda/bin to $PATH variable.

For anyone who is interested!

**Comment by kangkang59812** [comment]
@hinash88 so you mean you reinstall the pytorch to sovle the problem?

**Comment by hinash88** [comment]
Yes, from https://pytorch.org

**Comment by kangkang59812** [comment]
from source code?

**Comment by kangkang59812** [comment]
@hinash88 
'After that I updated ~/.bashrc by adding path to my installed anaconda/bin to $PATH variable.'

Could you show me how did you do exactly? Thanks a lot!!!

**Comment by hinash88** [comment]
Stable-> Linux->conda->python2.7->CUDA from (https://pytorch.org/)

**Comment by hinash88** [comment]
Can you please confirm your CUDA version?
