### ISSUE TITLE
Output issues with WaveGAN generated audio

### ISSUE THREAD

**Issue by hinash88** [fancoo/WaveGAN-pytorch#4]
Hi,

I successfully got the output after running this WaveGAN code. However the output audio is not correct.

1- I am getting audios of 1 sec for the given piano and drums dataset but this audio is nothing but a mouse click sound.

2- When I increase the dataset size for more than 100 examples as in case for [sc09](http://deepyeti.ucsd.edu/cdonahue/sc09.tar.gz) the code crashes and ubuntu restarts without showing any error. Due to small training dataset, I can not even increase batch size (since BATCH_NUM is dependent on it ).

3- I get this error (IndexError: too many indices for array) for the following lines. 
` D_cost_train_epoch.append(D_cost_train.data.numpy()[0])`
So I have removed array subscript. My loss curves are way too high of order 1e20.

These are the details of my parameters for [Drum dataset ](http://deepyeti.ucsd.edu/cdonahue/wavegan/data/drums.tar.gz) 
EPOCH = 500, Training dataset = 80 items, batch_size = 10, ngpus = 3
[INFO] 86m 27s D_cost_train:1303189041368655200256.0000 | D_wass_train:411356794.6667 | D_cost_valid:1309994062502480314368.0000 | D_wass_valid:99328792.5333 | G_cost:1336346464.0000

Can anybody please tell me what i am doing wrong?

**Comment by mazzzystar** [comment]
* 1.How long did you run the training process? Do you have loss curve or log?
* 2.This may because the `BATCH_SIZE` too large for > 100 examples,  and the procedure just out of memory, try to decrease the `BATCH_SIZE` lower than `64`
* 3.This loss is inn unusual, can I see the loss of the first epoch ? I suspect it's because the wrong `weight initial` for the networks.

**Comment by hinash88** [comment]
I have attached loss curve
![loss_curve](https://user-images.githubusercontent.com/47848681/53317462-10c2b800-390f-11e9-937e-952029cb5e5f.png)

-The loss of first epoch:
Starting training...EPOCHS=500, BATCH_SIZE=10, BATCH_NUM=6
0m 0s Epoch: 1/500
0m 5s Epoch=1 Batch: 1/6 D_c:11.1454 | D_w:3.9367 | G:1.0353
0m 7s Epoch=1 Batch: 2/6 D_c:-26.8214 | D_w:52.2886 | G:81.3630
0m 9s Epoch=1 Batch: 3/6 D_c:3160.8293 | D_w:136.8761 | G:16.0518
0m 10s Epoch=1 Batch: 4/6 D_c:19646.3164 | D_w:119.0609 | G:-340.4986
0m 12s Epoch=1 Batch: 5/6 D_c:83572.2422 | D_w:562.0609 | G:594.1994
0m 14s Epoch=1 Batch: 6/6 D_c:756582.3750 | D_w:864.4681 | G:1173.3860
0m 14s D_cost_train:70438.3109 | D_wass_train:185.0586 | D_cost_valid:138970.3153 | D_wass_valid:254.7478 | G_cost:254.2561

- Training time as I mentioned above is 86 min
- batch size is 10 for the above drum dataset with 80n items.

Moreover for Piano dataset, since the training examples are total 19 and training set after splitting is even less. So due to the following code. One can not increase batch_size >10
`BATCH_NUM = TOTAL_TRAIN_SAMPLES // batch_size`
`if i % (BATCH_NUM // 5) == 0:
            LOGGER.info("{} Epoch={} Batch: {}/{} D_c:{:.4f} | D_w:{:.4f} | G:{:.4f}".format(time_since(start), epoch,`

Othewise, the code gives division by zero error

**Comment by mazzzystar** [comment]
```
BATCH_SIZE=10, BATCH_NUM=6
```
I saw there are about 2400+ audio pieces in  `Drum` dataset, why your total training file is `10 * 6= 60`?

And the same, `Piano` dataset also contains pieces far larger than 19,  as I remember. (Even it's below 19, you can split the long audio sentences into small pieces each of 1 second). So you may need to check your dataset.

**Comment by hinash88** [comment]
Thank you for your time and reply. Actually when I increase dataset count to more than 100. the code crashes and ubuntu restarts without showing any error.

**Comment by mazzzystar** [comment]
Seems to be out of memory, sorry without log I can't give you a correct response.

**Comment by hinash88** [comment]
[model.log](https://github.com/mazzzystar/WaveGAN-pytorch/files/2904123/model.log)
I am sending you my syslog and model.log file. The last timestamp shows the output when my ubuntu crashed.

Quick review of details:
python3.5, CUDA10.0, Driver version 410.79, 3 x  GeForce RTX 2080 Ti, 
[syslog.log](https://github.com/mazzzystar/WaveGAN-pytorch/files/2904115/syslog.log)

[dataset = ](http://deepyeti.ucsd.edu/cdonahue/wavegan/data/drums.tar.gz) with 2000 examples. batch_size =16

**Comment by mazzzystar** [comment]
Sorry I mean the model log, I can't read any `error` in linux log file.
Have you tried the `sc09` dataset first, as my project suggested ?  If `sc09` can run successfully, then it's obviously not the issue of project itself.

**Comment by hinash88** [comment]
I updated my comment. please check model.log file.
I also checked it with sc09 dataset. Same issue, system crashes and restarts.

**Comment by mazzzystar** [comment]
```Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=16, BATCH_NUM=0
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=16, BATCH_NUM=0
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=16, BATCH_NUM=0
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=16, BATCH_NUM=0
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=16, BATCH_NUM=0
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=16, BATCH_NUM=0
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=16, BATCH_NUM=0
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=10, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=9, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=9, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=9, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=9, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=9, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=9, BATCH_NUM=1
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=6, BATCH_NUM=2
0m 0s Epoch: 1/180
Saving configurations...
Loading audio data...
Starting training...EPOCHS=180, BATCH_SIZE=6, BATCH_NUM=2
```
Why your data loading module loads data with various `BATCH_SIZE` at the same time ? Have you change the implementation of loading data ?

**Comment by hinash88** [comment]
No, I didnot change anything. The log that you showed here there were division by zero errors. so I had to reduce the batch_size. since with BATCH_NUM 0 the code gives division by zero error. and it is due to the fact that dataset is samller.
With larger dataset where e.g. BATCH_NUM=117, system restarts

**Comment by mazzzystar** [comment]
Would you mind just create a new folder, download the code and follow the [quick-start](https://github.com/mazzzystar/WaveGAN-pytorch#quick-start) to train `sc09` first ?  Do not modify anything and wait for the error log and then paste it here.

**Comment by hinash88** [comment]
This is the error: 
`Traceback (most recent call last):
 File "train.py", line 176, in <module>
    D_cost_train_epoch.append(D_cost_train.data.numpy()[0])
IndexError: too many indices for array
`
and here is the model.log file for sc09 data
[model.log](https://github.com/mazzzystar/WaveGAN-pytorch/files/2904269/model.log)

**Comment by mazzzystar** [comment]
For 
```
D_cost_train_epoch.append(D_cost_train.data.numpy()[0]
```

I wrote the code in PyTorch 0.4,  you just need to remove that `[0]` as PyTorch 1.0 does not support that style.

If still occurs the same error `IndexError: too many indices for array`, just remove all these `[0]`.

**Comment by mazzzystar** [comment]
I update my code for PyTorch 1.0 support. (not test yet)

**Comment by hinash88** [comment]
Thank you so much for your time. The problem was arising because of using my 3rd GPU which I don't know why. Now, I have been able to run the code with 2 GPUs and sc09 dataset with training example more than 2000. The training is still on and the cost is way too high. Here is the log:
[model.log](https://github.com/mazzzystar/WaveGAN-pytorch/files/2904991/model.log)

**Comment by mazzzystar** [comment]
How about the result running on a single GPU ?

**Comment by hinash88** [comment]
You were right, with one GPU the code is working perfectly as expected. But why not with multiple GPUs?

**Comment by hinash88** [comment]
Yes, It worked. But why not with Multiple GPUs?

**Comment by mazzzystar** [comment]
Sorry I don't know. I used a Machine Learning Platform which support multi-GPU by command-line and it worked fine.

**Comment by hinash88** [comment]
Thank you so much for your kind replies and time.

**Comment by aaxwaz** [comment]
I am getting reasonable losses when I used single GPU to train, but when switching to 2 gpus, it will give extremely large losses and distances, which seemed failed ...
